name: GitHub Actions Demo
on: [push]
jobs:
  Main-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"
      - run: sudo apt install nodejs
      - run: git clone "https://github.com/fmillerwork/basic-unit-tests-jest.git"
      - run: cd basic-unit-tests-jest
      - run: npm install
      - run: npm test
